### ISSUE TITLE
不同模块的类可以交叉编译吗？

### ISSUE THREAD

**Issue by neilbowman666** [shuaicj/zuul-auth-example#3]
作者大大：
您好。
拜读您的代码，发现有A模块使用B模块类的情况，请问此情况交叉编译可以通过吗？将不同子模块部署在微服务容器中的时候会不会影响其作用域？
谢谢。

**Comment by shuaicj** [comment]
该项目中的可运行模块都是spring boot应用，用mvn package可以编译生成各自的jar包；每个spring boot应用都是可独立运行的，无论是同时放在同一主机上或是同一docker container中，运行互不影响。
