### ISSUE TITLE
token user/password?

### ISSUE THREAD

**Issue by zaszlo** [shuaicj/zuul-auth-example#4]
Hi!

Thanks for this good plain example, it feels good to be able to look over some examples here... because of examples like this I thank God. 

Comparing with another one that too follows the JWT standard:
https://medium.com/@nydiarra/secure-a-spring-boot-rest-api-with-json-web-token-reference-to-angular-integration-e57a25806c50
I get the question of why has that one a token client/password, like:
`curl client:secret@localhost:8080/oauth/token -d grant_type=password -d username=user -d password=pwd`
And this examplle does not uses one at all. In the auth-center's application.yaml there is a secret but couldn't find the client and seems like this example simplifies this step. But isn't this client/secret thing a JWT standard?

Thanks for clarifying!

**Comment by shuaicj** [comment]
Sorry that the link you gave is broken so i can't see the details. 

But according to the key word `grant_type=password`, i guess the example you mentioned is probably showing how to integrate JWT token with OAuth2 Framework, which uses concepts like `grant_type` and `client_id`. 

You can dive into this doc [http://www.rfcreader.com/#rfc6749](http://www.rfcreader.com/#rfc6749) for details, though OAuth 2.0 is a giant monster and suitable for super enterprise systems in my opinion, which is the reason why it's not in my example. 

There is a post talking about this on Spring's Github page [https://github.com/spring-projects/spring-security-oauth/issues/368](https://github.com/spring-projects/spring-security-oauth/issues/368).

Hope my answer can help you.

**Comment by zaszlo** [comment]
Yes it was helpful, particularly the last link from Spring's Github page that states clearly that the two are different, JWT stands on its own without these additional authorization headers.

Thank you again!
