### ISSUE TITLE
loopholes in backend-service security

### ISSUE THREAD

**Issue by vikasgargvi** [shuaicj/zuul-auth-example#7]
localhost:8080/backend/admin or /user works fine, it requires authorization.
But by adding "/" at the end or url like "localhost:8080/backend/admin/" it bypasses the security.

**Comment by shuaicj** [comment]
Fixed in commit [bafe28d](https://github.com/shuaicj/zuul-auth-example/commit/bafe28d0541d2abe9f800c35e837c512e5f72b9d). Thanks a lot.
