### ISSUE TITLE
Database integration

### ISSUE THREAD

**Issue by charIeszhao** [shuaicj/zuul-auth-example#8]
你好 shuaicj，

非常感谢你的例子，精简又实用。你代码里面的东西我基本上都看明白了，不过作为一个Spring Boot菜鸟，我不太明白如何将数据库跟你的代码关联起来。目前我运行你的代码无法正常得到token，总是返回401错误，我猜是由于缺少数据库配置导致的吧？毕竟提交上去的用户名和密码要验证的，不过我没看到验证用户名密码这部分的代码在哪里。

我不知道是否可以直接在这里以issue的方式提问，所以麻烦再稍微解释一下这里面的逻辑。是否缺少了一些东西，还是说哪里我仍然没看懂，望指教。

多谢！

Hi shuaicj,

Thanks for your example. I've read all the code but I still haven't figured out the way I can connect your code to a database instance. Currently when posting username and password to “/login”, I always get a 401 error. I guess that's probably because the project hasn't really been connected to a database, and there's no way it can verify the username and password I sent.

So can you please kindly elaborate more on the database integration, or show me how I can resolve the 401 issue? I'm a noob to spring boot, and I will appreciate if you can point out if there's anything I missed.

Thank you!

**Comment by shuaicj** [comment]
Spring Security支持多种authentication的方式，常用的有in-memory authentication和jdbc authentication。一般test或demo的目的话使用in-memory的方式较为简单快捷，我这里也是如此，参见[SecurityConfig.java](https://github.com/shuaicj/zuul-auth-example/blob/master/auth-center/src/main/java/shuaicj/example/security/auth/SecurityConfig.java#L36) `auth.inMemoryAuthentication()`。

如上面源代码里可以看到，我已经内置了两个用户admin和shuaicj，按照我的README操作的话是可以直接login的，不清楚你的具体情况为什么login失败。

如果要用数据库的话，可用 `auth.jdbcAuthentication()` 进行相关配置。
